django_cart/cart/urls.py
# Filename  : urls.py
# Date  : 2018/9/27
from django.conf.urls import url

from cart import views

urlpatterns = [
	url(r'add_cart/', views.add_cart, name='add_cart'),
	# 	刷新价格
	url(r'^f_price/', views.f_price, name='f_price'),
	# 购物车
	url(r'^cart/', views.cart, name='cart'),

]

django_cart/day53Django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from day53Django_project import settings

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^users/', include('users.urls', namespace='users')),
	url(r'^goods/', include('goods.urls', namespace='goods')),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^orders/', include('orders.urls', namespace='orders'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_cart/goods/urls.py
# Filename  : urls.py
# Date  : 2018/9/27
from django.conf.urls import url

from goods import views

urlpatterns = [
	# 	商品详情
	url(r'^goods_detail/(\d+)/', views.goods_detail, name='goods_detail')

]

django_cart/orders/urls.py
# Filename  : urls.py
# Date  : 2018/9/27
from django.conf.urls import url

from orders import views

urlpatterns = [
	# 	下单
	url(r'^order/', views.order, name='order'),

]

django_cart/users/urls.py
# Filename  : urls.py
# Date  : 2018/9/26
from django.conf.urls import url

from users import views

urlpatterns = [
	url(r'^index/', views.index, name='index'),
	url(r'^login/', views.login, name='login'),
	url(r'^register/', views.register, name='register'),
	url(r'^base/', views.base, name='base'),
]

django_cart/cart/models.py
from django.db import models


# Create your models here.
from goods.models import Goods
from users.models import User


class ShoppingCart(models.Model):
	"""
	购物车
	"""
	user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
	goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
	nums = models.IntegerField(default=0, verbose_name='数量')
	add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
	is_select = models.BooleanField(default=True)

	class Meta:
		db_table = 'f_shopping_cart'

django_cart/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render


# Create your views here.
from cart.models import ShoppingCart
from goods.models import Goods


def add_cart(request):
	if request.method == 'POST':
		# 添加到session中数据格式为：
		# key==>goods
		# value==>[[id1，num, 1],[id2,num, 0],[id3,num, 1]...]
		# id商品的id num商品数量 1或0 商品选中或未选中（在结算页面起作用）
		# 1.1添加到购物车的数据，其实就是添加到session中
		# 1.2 如果商品已加入到session中，就修改session中商品的个数
		# 1.3 如果商品没有添加到session中，则添加

		# 获取从ajax中传递商品的id和商品个数
		goods_id = request.POST.get('goods_id')
		goods_num = request.POST.get('goods_num')
		# 组装存储的数据结构
		goods_list = [goods_id, goods_num, 1]
		# 判断在session中是否存储了商品信息
		if request.session.get('goods'):
			# 标识符：用于判断当前加入到购物车的商品
			# 如果购物车已经存在了该商品，则修改flag为1，否则flag还是为0
			flag = 0
			# 说明购物车已存储了商品信息
			seisson_goods = request.session['goods']
			for goods in seisson_goods:
				# 循环判断，判断加入到session中的商品是否已经存在于session中
				if goods_id == goods[0]:
					goods[1] = int(goods[1]) + int(goods_num)
					# 标识符，修改session中的商品后，标识符修改为1
					flag = 1
			# flag为0，表示添加到session中的商品之前并没有添加
			if not flag:
				seisson_goods.append(goods_list)
			# 	修改成功session中商品的信息
			request.session['goods'] = seisson_goods
			cart_count = len(seisson_goods)

		else:
			# 说明购物车还没有存储商品信息
			data = []
			data.append(goods_list)
			request.session['goods'] = data
			cart_count = 1

		return JsonResponse({'cde': 200, 'cart_count': cart_count})


def cart(request):
	if request.method == 'GET':
		# 需要判断用户是否登录，session['user_id']
		# 1、如果登录，则购物车展示当前登录用户的购物车中的数据
		# 2、如果没有登录，则购物车页面中展示session的数据
		user_id = request.session.get('user_id')
		if user_id:
			# 	登录系统用户
			shop_cart = ShoppingCart.objects.filter(user_id=user_id)
			goods_all = [(cart.goods, cart.is_select, cart.nums) for cart in shop_cart]
			return render(request, 'cart.html', {'goods_all': goods_all})
		else:
			# 没有登录
			session_goods = request.session.get('goods')
			# 拿到session中所有商品id值
			if session_goods:
				goods_all = [(Goods.objects.get(pk=good[0]), good[2], good[1])
				             for good in session_goods]
			else:
				goods_all = ''

			return render(request, 'cart.html', {'goods_all': goods_all})


def f_price(request):
	"""
	返回购物车或session中商品的价格，和总价
	{key1:[[id1, price1],[id2, price2]],key2:total_price}
	"""

	user_id = request.session.get('user_id')

	if user_id:
		# 获取当前登录系统的用户购物车信息
		carts = ShoppingCart.objects.filter(user_id=user_id)
		cart_data = {}
		cart_data['goods_price'] = [(cart.goods_id, cart.nums*cart.goods.shop_price)
		 for cart in carts]

		all_price = 0
		# 总的价格
		for cart in carts:
			if cart.is_select:
				all_price += cart.nums*cart.goods.shop_price
		cart_data['all_price'] = all_price
	else:
		# 拿到session中所有商品信息
		session_goods = request.session.get('goods')
		# 返回数据结构，{'goods_price':[[id1,price1],[id2,price2],...]}
		cart_data = {}
		data_all = []
		# 计算总价
		all_price = 0
		for goods in session_goods:
			data = []
			data.append(goods[0])
			g = Goods.objects.get(pk=goods[0])
			data.append(int(goods[1]) * g.shop_price)
			data_all.append(data)
			# 判断如果商品勾选了，才计算总价格
			if goods[2]:
				all_price += int(goods[1]) * g.shop_price
		cart_data['goods_price'] = data_all
		cart_data['all_price'] = all_price
	return JsonResponse({'code': 200, 'cart_data': cart_data})

django_cart/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titile %}
        {% endblock %}
    </title>
    {% block css_js %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
    <script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
    {% endblock %}
</head>
<body>
    {% block header %}
        <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
{#                {% if request.session.is_login %}#}
				<div class="login_info fl" style="">
					欢迎您：<em></em>
				</div>
{#                {% else %}#}
				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
{#                {% endif %}#}
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    {% endblock %}

    {% block search %}
        <div class="search_bar clearfix">
		<a href="{% url 'users:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
    {% endblock %}

    {% block body %}
    {% endblock %}

    {% block footer %}
        <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {% endblock %}
</body>
</html>

<script>
    {#$.get('', function (data) {#}
    {#    console.log(data)#}
    {#    if (data.user.username) {#}
    {#        alert('xx')#}
    {#    $('.login_info em').html(data.user.username);#}
    {#    $('.login_info').attr("style","display: inline");#}
    {#    $('.login_btn').attr("style","")#}
    {#    }#}
    {##}
    var csrf = $('input[name="csrfmiddlewaretoken"]').val()
    $.ajax({
        url:'/users/base/',
        type:'POST',
        dataTypes : 'json',
        headers:{'X-CSRFToken': csrf},
        success:function (data) {
            console.log(data)
            if (data.user.username) {
             $('.login_info em').html(data.user.username);
             $('.login_info').attr("style","display: inline");
             $('.login_btn').attr("style","")
            }
        },
        error:function (data) {
            alert('创建失败')

        }

    });
</script>

django_cart/templates/cart.html
{% extends 'base.html' %}
        {% block titile %}
            天天生鲜-购物车
        {% endblock %}

{% block search %}
	<div class="search_bar clearfix">
		<a href="{% url 'users:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
{% endblock %}

{% block body %}
	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    {% if goods_all %}
        {% for goods in goods_all %}
            <ul class="cart_list_td clearfix">
                <li class="col01"><input type="checkbox" name="" {% if goods.1 %}checked{% endif %}></li>
                <li class="col02"><img src="/media/{{ goods.0.goods_front_image }}"></li>
                <li class="col03">{{ goods.0.name }}<br><em>{{ goods.0.shop_price }}元/500g</em></li>
                <li class="col04">500g</li>
                <li class="col05">{{ goods.0.shop_price }}元</li>
                <li class="col06">
                    <div class="num_add">
                        <a href="javascript:;" class="add fl">+</a>
                        <input type="text" class="num_show fl" value="{{ goods.2 }}">
                        <a href="javascript:;" class="minus fl">-</a>
                    </div>
                </li>
                <li class="col07" id="goods_{{ goods.0.id }}">元</li>
                <li class="col08"><a href="javascript:;">删除</a></li>
            </ul>
        {% endfor %}
    {% endif %}

	<script>
        $.get('/cart/f_price/', function (data) {
            if (data.code == '200'){
                for(var i=0; i<data.cart_data.goods_price.length; i++){
                    price = data.cart_data.goods_price[i][1] + '元'
                    $('#goods_' + data.cart_data.goods_price[i][0]).html(price)
                }
                $('#total_price em').html(data.cart_data.all_price +'元')
                $('.total_count em').html(data.cart_data.goods_price.length)
                $('#total_price b').html(data.cart_data.goods_price.length)
            }
        })

    </script>
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03" id="total_price">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="{% url 'orders:order' %}">去结算</a></li>
	</ul>

{% endblock %}

django_cart/templates/detail.html
{% extends 'base.html' %}
{% block titile %}
	天天生鲜-商品详情
{% endblock %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/media/{{ goods.goods_front_image }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.name }}</h3>
			<p>{{ goods.goods_brief }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.shop_price }}</em></span>
				<span class="show_unit">单  位：500g</span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span> <span>库  存：{{ goods.goods_nums }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr" onclick="add_goods({{ goods.shop_price }});">+</a>
					<a href="javascript:;" class="minus fr" onclick="sub_goods({{ goods.shop_price }});">-</a>
				<script>
                function add_goods(price) {
                    {#获取默认的个数#}
                    var num =  $('.num_show').val()
                    {#计算总价#}
                    var total = (parseInt(num)+1)*price
                      {#修改总价  #}
                    $('.total em').html(total+'元')
                        {#修改商品个数#}
                    $('.num_show').val(parseInt(num)+1)

                }


                function sub_goods(price) {
                    var num = $('.num_show').val()
                    var count = parseInt(num) -1
                    if (count > 0){
                        var total = count*price
                        $('.total em').html(total+'元')
                        $('.num_show').val(count)
                    }
                }
            </script>
                </div>
			</div>

			<div class="total">总价：<em>{{ goods.shop_price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn" >立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart" onclick="add_to_cart({{ goods.id }})">加入购物车</a>
			</div>
            {% csrf_token %}
            <script>
                function add_to_cart(id) {
                    var csrf = $('input[name ="csrfmiddlewaretoken"]').val()
                    var num = $('.num_show').val()
                    $.ajax({
                        {#请求到的地址#}
                        url:'/cart/add_cart/',
                        dataType: 'json',
                        type: 'POST',
                        headers:{'X-CSRFToken': csrf},
                        {#传参#}
                        data: {'goods_id':id, 'goods_num':num},
                        success:function (data) {
                            console(data)
                        },
                        error:function (data) {

                        }
                    })
                }
            </script>
		</div>
	</div>

	<div class="main_wrap clearfix">
{#		<div class="l_wrap fl clearfix">#}
{#			<div class="new_goods">#}
{#				<h3>新品推荐</h3>#}
{#				<ul>#}
{#					<li>#}
{#						<a href="#"><img src="/static/images/goods/goods001.jpg"></a>#}
{#						<h4><a href="#">进口柠檬</a></h4>#}
{#						<div class="prize">￥3.90</div>#}
{#					</li>#}
{#					<li>#}
{#						<a href="#"><img src="/static/images/goods/goods002.jpg"></a>#}
{#						<h4><a href="#">玫瑰香葡萄</a></h4>#}
{#						<div class="prize">￥16.80</div>#}
{#					</li>#}
{#				</ul>#}
{#			</div>#}
{#		</div>#}

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_desc|safe }} </dd>
				</dl>
			</div>

		</div>
	</div>

	<div class="add_jump"></div>

	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function() {
					$(".add_jump").fadeOut('fast',function(){
						$('#show_count').html(2);
					});

			});
		})
	</script>
	
{% endblock %}

django_cart/templates/index.html
{% extends 'base.html' %}

{% block titile %}
    天天生鲜-首页
{% endblock %}


{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

    {% for key,value in data_all.items %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">
                {% for type in category_types %}
                    {% ifequal type.0 value.0.category.category_type %}
                        {{ type.1 }}
                    {% endifequal %}
                {% endfor %}
            </h3>
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#				<a href="#">鲜芒</a>#}
{#				<a href="#">加州提子</a>#}
{#				<a href="#">亚马逊牛油果</a>#}
{#			</div>#}
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>
		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{ value.0.category.category_front_image }}"></div>
			<ul class="goods_list fl">
                {% for good in value %}
				<li>
					<h4><a href="{% url 'goods:goods_detail' good.id %}">{{ good.name }}</a></h4>
					<a href="{% url 'goods:goods_detail' good.id %}"><img src="/media/{{ good.goods_front_image }}"></a>
					<div class="prize">¥ {{ good.shop_price }}</div>
				</li>
                {% endfor %}

			</ul>
		    </div>
        {% endfor %}
</div>

	<script type="text/javascript" src="/static/js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

django_cart/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'users:index' %}" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error" style="display: inline;">{{ form.errors.username }}</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error" style="display: inline;">{{ form.errors.password }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

django_cart/templates/register.html
{% extends 'base.html' %}
{% block titile %}
    天天生鲜-注册
{% endblock %}



{% block header %}
{% endblock %}

{% block search %}
{% endblock %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'users:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post">
                    {% csrf_token %}

				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="username" id="user_name">
						<span class="error_tip" style="display: inline;">{{ form.errors.username }}</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="password" id="pwd">
						<span class="error_tip" style="display: inline;">{{ form.errors.password }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="password2" id="cpwd">
						<span class="error_tip" style="display: inline;">{{ form.errors.password2 }}</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip" style="display: inline;">{{ form.errors.email }}</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2" style="display: inline;">{{ form.errors.allow }}</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{% endblock %}

django_cart/templates/user_center_site.html
{% extends 'base.html' %}
{% block titile %}
    天天生鲜-用户中心
{% endblock %}
	{% block search %}

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
    {% endblock %}
{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="user_center_info.html">· 个人信息</a></li>
				<li><a href="user_center_order.html">· 全部订单</a></li>
				<li><a href="user_center_site.html" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form>
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>


{% endblock %}